%aggregated_spectrum = aggregate('percentile', 95);
path = char(strcat(pwd,'\data\workflow\aggregated_spectrum.mat'));
%save(path,'aggregated_spectrum');
load(path);
%division_points = div_points(aggregated_spectrum);
path = char(strcat(pwd,'\data\workflow\division_points.mat'));
%save(path,'division_points');
load(path);
spectrum_model = spectr_model(division_points,aggregated_spectrum);
path = char(strcat(pwd,'\data\workflow\spectrum_model.mat'));
%save(path,'spectrum_model');
load(path);
denoised_model = denoise(spectrum_model);
path = char(strcat(pwd,'\data\workflow\denoised_model.mat'));
%save(path,'denoised_model');
features = prepare_features(denoised_model);
path = char(strcat(pwd,'\data\workflow\features.mat'));
%save(path,'features');
merged_model = merge(features);
path = char(strcat(pwd,'\data\workflow\merged_model.mat'));
%save(path,'merged_model');